// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drfeeszmgjbohmfmwglt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyZmVlc3ptZ2pib2htZm13Z2x0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNzk0MTEsImV4cCI6MjA5MDY1NTQxMX0.uBD3klGcAUOFfxzGLmj9umXrHZNWGUvENnQ_77kuRe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});